import { useEffect, useState } from "react";
import {
  Mic,
  Square,
  FileText,
  Stethoscope,
  Pill,
  Sparkles,
  RotateCcw,
  MessageCircle,
  Send,
  User,
} from "lucide-react";
import AIBadge from "../components/ui/AIBadge";
import Tabs from "../components/ui/Tabs";
import Badge from "../components/ui/Badge";
import Modal from "../components/ui/Modal";
import EditablePrescriptionForm from "../components/ui/EditablePrescriptionForm";
import { useCoPilot } from "../hooks/useCoPilot";
import { usePatients } from "../hooks/usePatients";
import LoadingSpinner from "../components/ui/LoadingSpinner";
import { useToast } from "../context/ToastContext";

const SAMPLE = `Patient came in with persistent dry cough for the past 5 days. Reports mild fever and fatigue. No chest pain. Has history of seasonal allergies. On examination throat appears mildly red, chest is clear. Vitals stable.`;

export default function AICoPilot() {
  const [tab, setTab] = useState("soap");
  const [recording, setRecording] = useState(false);
  const [transcript, setTranscript] = useState(SAMPLE);
  const [showWhatsAppModal, setShowWhatsAppModal] = useState(false);
  const [patientSearch, setPatientSearch] = useState("");
  const [currentPrescription, setCurrentPrescription] = useState({
    medicines: [{ drug: "", dose: "", frequency: "", duration: "" }],
    notes: "",
  });
  const [selectedPatient, setSelectedPatient] = useState(null);

  const { soap, diagnosis, prescription, loading, error, generateSOAP } = useCoPilot();
  const { showToast } = useToast();
  const { data: patients, loading: patientLoading } = usePatients({
    search: patientSearch,
    riskLevel: "",
  });

  useEffect(() => {
    if (prescription && prescription.length > 0) {
      setCurrentPrescription({
        medicines: prescription.map((item) => ({
          drug: item.drug || item.name || "",
          dose: item.dose || "",
          frequency: item.frequency || "",
          duration: item.duration || "",
        })),
        notes: "Review and adjust before sharing with the patient.",
      });
    }
  }, [prescription, selectedPatient?.id]);

  useEffect(() => {
    if (!selectedPatient && patients && patients.length > 0) {
      setSelectedPatient(patients[0]);
    }
  }, [patients]);

  const sendPrescriptionViaWhatsApp = (patient) => {
    const rx = currentPrescription?.medicines?.length
      ? currentPrescription
      : { medicines: prescription };

    if (!rx || !rx.medicines || rx.medicines.length === 0) {
      alert("Please generate and edit a prescription first");
      return;
    }
    if (!patient) {
      alert("Please select a patient first");
      return;
    }

    const message = `*🩺 NexaCare AI Prescription*

*Patient:* ${patient.name}
*Date:* ${new Date().toLocaleDateString("en-IN")}
*Generated by:* AI Co-Pilot

*Medicines:*
${rx.medicines
  .map(
    (r, i) =>
      `${i + 1}. *${r.drug}*
   Dosage: ${r.dose}
   Frequency: ${r.frequency}
   Duration: ${r.duration}`,
  )
  .join("\n\n")}

*Instructions:*
${currentPrescription.notes || "Follow prescription directions carefully."}

*⚠️ Important Instructions:*
• Take medicines as prescribed
• Complete the full course
• Do not stop medication without consulting doctor
• Report any side effects immediately
• Follow up with your doctor

*Generated by AI Co-Pilot - Always consult your doctor*

_NexaCare - Your Health, Our Priority_`;

    console.log("Sending prescription via WhatsApp to:", patient.phone);
    console.log("Message:", message);

    alert(`Prescription sent successfully to ${patient.name} via WhatsApp!`);
    setShowWhatsAppModal(false);
  };

  return (
    <div className="space-y-5">
      <div>
        <h1 className="text-2xl font-display font-bold flex items-center gap-2">
          AI Co-Pilot <AIBadge />
        </h1>
        <p className="text-sm text-muted-foreground mt-1">
          Live consultation transcription with AI-drafted SOAP notes, differential Dx and
          prescription suggestions.
        </p>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-2 gap-5">
        <div className="bg-card border border-border rounded-xl shadow-sm overflow-hidden">
          <div className="flex items-center justify-between px-5 py-4 border-b border-border">
            <div>
              <h3 className="font-display font-semibold">Live Transcript</h3>
              <p className="text-xs text-muted-foreground">Auto-captured from in-room mic</p>
            </div>
            <button
              onClick={() => setRecording(!recording)}
              className={`inline-flex items-center gap-2 px-4 py-2 rounded-lg text-sm font-medium ${
                recording
                  ? "bg-[var(--danger)] text-white"
                  : "bg-[var(--brand)] text-white hover:bg-[var(--brand-hover)]"
              }`}
            >
              {recording ? (
                <>
                  <Square size={14} />
                  Stop
                </>
              ) : (
                <>
                  <Mic size={14} />
                  Record
                </>
              )}
            </button>
          </div>
          <div className="p-5">
            {recording && (
              <div className="flex items-center gap-2 text-xs text-[var(--danger)] mb-3">
                <span className="w-2 h-2 rounded-full bg-[var(--danger)] animate-pulse"></span>
                Recording • 02:14
              </div>
            )}
            <textarea
              value={transcript}
              onChange={(e) => setTranscript(e.target.value)}
              className="w-full h-72 bg-surface rounded-lg p-4 text-sm outline-none resize-none border border-border focus:border-[var(--brand)] transition-colors"
            />
            <div className="flex gap-2 mt-3">
              <button
                onClick={() => generateSOAP(transcript)}
                className="flex-1 inline-flex items-center justify-center gap-2 px-4 py-2 bg-[var(--ai)] text-white rounded-lg text-sm font-medium hover:opacity-90"
              >
                <Sparkles size={14} />
                Generate AI Notes
              </button>
              <button
                onClick={() => setTranscript(SAMPLE)}
                className="px-3 py-2 bg-surface border border-border rounded-lg text-sm hover:bg-surface-alt"
              >
                <RotateCcw size={14} />
              </button>
            </div>
          </div>
        </div>

        <div className="bg-card border border-border rounded-xl shadow-sm overflow-hidden border-l-4 border-l-[var(--ai)]">
          <div className="px-5 pt-4">
            <div className="flex items-center gap-2 mb-3">
              <AIBadge label="AI Output" />
              <span className="text-xs text-muted-foreground">Always review before saving</span>
            </div>
            <Tabs
              active={tab}
              onChange={setTab}
              tabs={[
                { value: "soap", label: "SOAP Notes" },
                { value: "dx", label: "Diagnosis" },
                { value: "rx", label: "Prescription" },
              ]}
            />
            <div className="mt-4 rounded-3xl border border-border bg-surface px-4 py-4 text-sm text-foreground">
              <div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between">
                <div>
                  <div className="text-sm font-semibold">Current Patient</div>
                  <div className="text-xs text-muted-foreground">
                    Search and link this AI session to the right patient.
                  </div>
                </div>
                <div className="flex items-center gap-2">
                  <input
                    value={patientSearch}
                    onChange={(e) => setPatientSearch(e.target.value)}
                    placeholder="Search patient…"
                    className="min-w-[180px] rounded-lg border border-border bg-background px-3 py-2 text-sm text-foreground outline-none focus:border-[var(--brand)]"
                  />
                </div>
              </div>
              <div className="mt-3 grid gap-2 max-h-40 overflow-y-auto">
                {patientLoading ? (
                  <div className="text-sm text-muted-foreground">Loading patients…</div>
                ) : patients?.length ? (
                  patients.slice(0, 6).map((patient) => (
                    <button
                      key={patient.id}
                      type="button"
                      onClick={() => setSelectedPatient(patient)}
                      className={`w-full flex items-center justify-between rounded-2xl border px-3 py-2 text-left transition-colors ${
                        selectedPatient?.id === patient.id
                          ? "bg-[var(--brand)]/10 border-[var(--brand)]"
                          : "bg-white border-border hover:bg-surface-alt"
                      }`}
                    >
                      <span className="font-medium text-sm">{patient.name}</span>
                      <span className="text-xs text-muted-foreground">{patient.abhaId}</span>
                    </button>
                  ))
                ) : (
                  <div className="text-sm text-muted-foreground">No matching patients found.</div>
                )}
              </div>
            </div>
          </div>
          <div className="p-5 min-h-[420px]">
            {loading && <LoadingSpinner label="AI thinking…" />}
            {!loading && error && (
              <div className="text-center text-sm text-destructive py-16">
                <Sparkles className="mx-auto text-destructive mb-3" size={28} />
                Something went wrong while generating AI notes. Please try again.
              </div>
            )}
            {!loading && !soap && !error && (
              <div className="text-center text-sm text-muted-foreground py-16">
                <Sparkles className="mx-auto text-[var(--ai)] mb-3" size={28} />
                Click <strong>Generate AI Notes</strong> to draft SOAP, diagnosis and prescription.
              </div>
            )}
            {!loading && soap && tab === "soap" && (
              <div className="space-y-4 text-sm">
                {[
                  { k: "Subjective", v: soap.subjective, icon: FileText },
                  { k: "Objective", v: soap.objective, icon: Stethoscope },
                  { k: "Assessment", v: soap.assessment, icon: Sparkles },
                  { k: "Plan", v: soap.plan, icon: Pill },
                ].map((s) => (
                  <div key={s.k}>
                    <div className="flex items-center gap-2 text-xs font-semibold uppercase text-[var(--brand-active)] mb-1">
                      <s.icon size={12} />
                      {s.k}
                    </div>
                    <div className="text-foreground bg-surface rounded-lg p-3 leading-relaxed">
                      {s.v}
                    </div>
                  </div>
                ))}
              </div>
            )}
            {!loading && diagnosis.length > 0 && tab === "dx" && (
              <div className="space-y-3">
                {diagnosis.map((d) => (
                  <div key={d.code} className="bg-surface rounded-lg p-3">
                    <div className="flex items-center justify-between mb-2">
                      <div>
                        <div className="text-xs font-mono text-muted-foreground">{d.code}</div>
                        <div className="font-medium text-sm">{d.label}</div>
                      </div>
                      <Badge
                        variant={
                          d.confidence > 0.6
                            ? "success"
                            : d.confidence > 0.4
                              ? "warning"
                              : "default"
                        }
                      >
                        {(d.confidence * 100).toFixed(0)}%
                      </Badge>
                    </div>
                    <div className="h-1.5 bg-border rounded-full overflow-hidden">
                      <div
                        className="h-full bg-[var(--ai)]"
                        style={{ width: `${d.confidence * 100}%` }}
                      ></div>
                    </div>
                  </div>
                ))}
              </div>
            )}
            {!loading && prescription.length > 0 && tab === "rx" && (
              <div className="space-y-4">
                <div className="rounded-3xl border border-border bg-surface p-4">
                  <div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between mb-4">
                    <div>
                      <div className="text-sm font-semibold">Editable AI Prescription</div>
                      <div className="text-xs text-muted-foreground">
                        Review and tweak medication details before sending to the patient.
                      </div>
                    </div>
                    {selectedPatient ? (
                      <Badge variant="secondary" className="text-xs">
                        Patient: {selectedPatient.name}
                      </Badge>
                    ) : (
                      <Badge variant="outline" className="text-xs">
                        No patient selected
                      </Badge>
                    )}
                  </div>

                  <EditablePrescriptionForm
                    value={currentPrescription}
                    onChange={setCurrentPrescription}
                    patientId={selectedPatient?.id}
                  />

                  <div className="flex flex-col gap-2 sm:flex-row mt-4">
                    <button
                      onClick={() => {
                        if (!selectedPatient) {
                          alert("Select a current patient before sending");
                          return;
                        }
                        setShowWhatsAppModal(true);
                      }}
                      className="flex-1 inline-flex items-center justify-center gap-2 px-4 py-2 bg-green-600 text-white rounded-lg text-sm font-medium hover:bg-green-700 transition-colors"
                    >
                      <MessageCircle size={14} />
                      Send via WhatsApp
                    </button>
                    <button
                      onClick={() => showToast("AI prescription saved", "success")}
                      className="flex-1 inline-flex items-center justify-center gap-2 px-4 py-2 bg-[var(--brand)] text-white rounded-lg text-sm font-medium hover:bg-[var(--brand-hover)] transition-colors"
                    >
                      <Send size={14} />
                      Save Prescription
                    </button>
                  </div>
                </div>
              </div>
            )}
          </div>
        </div>
      </div>

      {/* WhatsApp Prescription Modal */}
      <Modal
        open={showWhatsAppModal}
        onClose={() => {
          setShowWhatsAppModal(false);
        }}
        title="Send Prescription via WhatsApp"
        width="max-w-lg"
      >
        <div className="space-y-4">
          <p className="text-sm text-muted-foreground">
            Select a patient to send the AI-generated prescription via WhatsApp
          </p>

          <div className="space-y-3 max-h-64 overflow-y-auto">
            {patients?.length ? (
              patients.slice(0, 6).map((patient) => (
                <div
                  key={patient.id}
                  className={`p-4 border rounded-lg cursor-pointer transition-colors ${
                    selectedPatient?.id === patient.id
                      ? "border-[var(--brand)] bg-[var(--brand)]/5"
                      : "border-border hover:bg-surface"
                  }`}
                  onClick={() => setSelectedPatient(patient)}
                >
                  <div className="flex items-center justify-between mb-2">
                    <div className="flex items-center gap-3">
                      <div className="w-8 h-8 rounded-full bg-[var(--brand)] text-white flex items-center justify-center">
                        <User size={14} />
                      </div>
                      <div>
                        <div className="font-medium text-sm">{patient.name}</div>
                        <div className="text-xs text-muted-foreground">{patient.phone}</div>
                      </div>
                    </div>
                    <Badge variant="info" className="text-xs">
                      {patient.abhaId}
                    </Badge>
                  </div>
                </div>
              ))
            ) : (
              <div className="text-sm text-muted-foreground">
                No patients available for selection.
              </div>
            )}
          </div>

          {selectedPatient && (
            <div className="flex gap-2 pt-4 border-t">
              <button
                onClick={() => sendPrescriptionViaWhatsApp(selectedPatient)}
                className="flex-1 inline-flex items-center justify-center gap-2 px-4 py-2 bg-green-600 text-white rounded-lg text-sm font-medium hover:bg-green-700"
              >
                <MessageCircle size={14} />
                Send to {selectedPatient.name}
              </button>
              <button
                onClick={() => {
                  setShowWhatsAppModal(false);
                  setSelectedPatient(null);
                }}
                className="px-4 py-2 bg-surface border border-border rounded-lg text-sm hover:bg-surface-alt"
              >
                Cancel
              </button>
            </div>
          )}
        </div>
      </Modal>
    </div>
  );
}
